### PR TITLE
Update to v0.10.0 & rerender (conda-smithy 2.4.0)

### PR DESCRIPTION
**Pull request by vtermanis**
MNT: Re-rendered with conda-smithy 2.4.0

Library changes:
- Support No-Op type (decoder only)
- Allow for object keys to be interned, saving memory if repeated (PY3 only)
- Use PyUnicode_FromStringAndSize instead of PyUnicode_DecodeUTF8 (decoder)
- Open file for writing, not appending (to/from json utility)
- Used more compact json encoding (to/from json utility)
- Enable object key interning (to/from json utility)

### CODE REVIEW

**Comment by vtermanis** [comment]
@ocefpaf / @conda-forge/core, I get for all appveyor builds:
```
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::anaconda-client-1.6.5-py_0'.
CondaError: Cannot link a source that does not exist. C:\Miniconda36-x64\Scripts\conda.exe
```

Do I need to do a re-render pull request first or is this a different problem?

**Comment by isuruf** [comment]
Yes, you need to rerender

**Comment by vtermanis** [comment]
Thanks @isuruf , I shall do that in a separate PR

**Comment by vtermanis** [comment]
.. or should I just add a commit to re-render in this pull request? (I don't mind, whatever is preferred.)

**Comment by isuruf** [comment]
You can do it in this PR.

**Pull request merged**
